### PR TITLE
Update Stack default version to 8.1.0

### PR DESCRIPTION
**Pull request by endorama**
This PR supersede #708 and updates default Stack version to `8.1.0` to align with latest release.

### CODE REVIEW

**Review by mtojek — COMMENTED** [review]
@endorama Could you please iterate on this and missing Kubernetes fields:

```
[1] field "kubernetes.namespace_uid" is undefined
[2] field "kubernetes.node.labels.beta_kubernetes_io/arch" is undefined
[3] field "kubernetes.node.labels.beta_kubernetes_io/os" is undefined
[4] field "kubernetes.node.labels.kubernetes_io/arch" is undefined
[5] field "kubernetes.node.labels.kubernetes_io/hostname" is undefined
[6] field "kubernetes.node.labels.kubernetes_io/os" is undefined
[7] field "kubernetes.node.labels.node-role_kubernetes_io/control-plane" is undefined
[8] field "kubernetes.node.labels.node-role_kubernetes_io/master" is undefined
[9] field "kubernetes.node.labels.node_kubernetes_io/exclude-from-external-load-balancers" is undefined
```

I guess you will find them in the elastic/integrations repository.

**Comment by endorama** [comment]
The failure is coming from kubernetes packages:
```
one or more errors found in documents stored in metrics-kubernetes.pod-ep data stream: [0] field "kubernetes.namespace_labels.kubernetes_io/metadata_name" is undefined
[1] field "kubernetes.namespace_uid" is undefined
[2] field "kubernetes.node.labels.beta_kubernetes_io/arch" is undefined
[3] field "kubernetes.node.labels.beta_kubernetes_io/os" is undefined
[4] field "kubernetes.node.labels.kubernetes_io/arch" is undefined
[5] field "kubernetes.node.labels.kubernetes_io/hostname" is undefined
[6] field "kubernetes.node.labels.kubernetes_io/os" is undefined
[7] field "kubernetes.node.labels.node-role_kubernetes_io/control-plane" is undefined
[8] field "kubernetes.node.labels.node-role_kubernetes_io/master" is undefined
[9] field "kubernetes.node.labels.node_kubernetes_io/exclude-from-external-load-balancers" is undefined
[10] field "kubernetes.node.uid" is undefined
```

**Comment by mtojek** [comment]
@endorama I kindly asked you to adjust the kubernetes package [here](https://github.com/elastic/elastic-package/pull/724#pullrequestreview-904887230).

**Comment by endorama** [comment]
GitHub cache hit again :sweat: I'm on it

**Review by mtojek — APPROVED** [review]

**Pull request merged**
