### PR TITLE
DO NOT MERGE - Enable logsdb by default

### PR DESCRIPTION
**Pull request by jsoriano**

### CODE REVIEW

**Comment by jsoriano** [comment]
test integrations

**Comment by felixbarny** [comment]
The aws_logs tests have failed. But it seems this may be a transient issue?

```
Error: error running package system tests: could not complete test run: could not setup service: Terraform deployer is unhealthy: container (ID: 30ac88ce839bb77f51ef45c52131791824f284e467c6c4098f3af74824142d4a) exited with code 1
```

Could you try to re-run the tests?

**Comment by jsoriano** [comment]
Yes, this is a known issue that can be ignored by now.

**Comment by felixbarny** [comment]
Did this error cause other tests to not run? Or can we say that all non-flaky integrations tests have been executed successfully with LogsDB enabled?

**Comment by jsoriano** [comment]
Yes, we can say this has been quite successful, no related failures seen here or in the integrations repo https://github.com/elastic/integrations/pull/10353.

**Comment by jsoriano** [comment]
Ah no sorry, I didn't change the stack version :facepalm: so hardly anything has been tested with logsdb, it is only enabled with 8.15.

**Comment by jsoriano** [comment]
Pushed change to force testing with 8.15 https://github.com/elastic/integrations/pull/10353

**Pull request closed without merging**
