### PR TITLE
Support "input packages"

### PR DESCRIPTION
**Pull request by mtojek**
Meta-issue: https://github.com/elastic/package-spec/issues/319

With this PR, elastic-package allows for building the input package, validating it, and exposing it behind the Package Registry. As the Fleet is not ready yet we can see this result:

```
[2022-06-03T07:01:13.826Z] 2022/06/03 07:01:13 DEBUG POST http://127.0.0.1:5601/api/fleet/epm/packages/sql_input-0.2.0
[2022-06-03T07:01:18.022Z] Installed assets:
[2022-06-03T07:01:18.023Z] Done
```

In the [follow up](https://github.com/elastic/elastic-package/pull/840) I will focus on improving field validation, rendering fields table, and importing fields.

### CODE REVIEW

**Comment by mtojek** [comment]
Hm, based on test errors I deduce that we have to release a new revision of package-spec...

**Comment by jsoriano** [comment]
Preparing release of the spec https://github.com/elastic/package-spec/pull/329

**Review by jsoriano — APPROVED** [review]

**Review by jsoriano — APPROVED** [review]

**Pull request merged**
