### PR TITLE
Avoid trying to adjust dropped events on test results

### PR DESCRIPTION
**Pull request by jsoriano**
Pipelines can drop events, and they appear as null values in the test result, avoid trying to convert these null events into `common.MapStr`, producing errors like:
```
ERROR: verifying test result failed: comparing test results failed: can't adjust test results: can't unmarshal event: unexpected end of JSON input
```

### CODE REVIEW

**Review by mtojek — APPROVED** [review]
It smells like a workaround, but in general all runners (test framework) require refactoring. If it doesn't harm other cases, I'm good with this change. Maybe just drop comment on this line, why is it necessary.

**Comment by mtojek** [comment]
@jsoriano Do you plan to continue working on this PR or should it be closed?

**Comment by jsoriano** [comment]
Let's close it and continue droping the events on the pipeline.

**Comment by jsoriano** [comment]
Oh, I closed this thinking that it was #380 facepalm reopening, this is needed for elastic/integrations#1145.

**Comment by jsoriano** [comment]
Reopened again as https://github.com/elastic/elastic-package/pull/397

**Pull request closed without merging**
