### PR TITLE
Adding kube resources required by cloudbeat

### PR DESCRIPTION
**Pull request by oren-zohar**
**what this RP does**
Following https://github.com/elastic/elastic-package/pull/795, adding required `kube-api` resources.

___

- Related: https://github.com/elastic/security-team/issues/3682

### CODE REVIEW

**Review by DaveSys911 — APPROVED** [review]
LGTM

**Comment by jsoriano** [comment]
@elastic/obs-cloudnative-monitoring could you please take a look to this change too? Thanks!

**Review by jsoriano — APPROVED** [review]

**Review by ChrsMark — APPROVED** [review]
lgtm! Keep in mind that the "official" manifests are hosted at https://github.com/elastic/elastic-agent/tree/e80913a7bdbdec0cad94ef9f585b59eec6ead46f/deploy/kubernetes and the documentation that may require updates at https://www.elastic.co/guide/en/fleet/master/running-on-kubernetes-managed-by-fleet.html

**Comment by mtojek** [comment]
@ChrsMark Do you know how far we are from the official? Just curious.

@jsoriano Do you think that we should create a new release for this change? It might be good not to keep it parked for too long.

**Comment by jsoriano** [comment]
> @jsoriano Do you think that we should create a new release for this change? It might be good not to keep it parked for too long.

Agree, tag pushed.

**Comment by ChrsMark** [comment]
> @ChrsMark Do you know how far we are from the official? Just curious.

What we compare here? https://github.com/elastic/elastic-agent/tree/e80913a7bdbdec0cad94ef9f585b59eec6ead46f/deploy/kubernetes is the official Daemnoset we propose to our users at https://www.elastic.co/guide/en/fleet/master/running-on-kubernetes-managed-by-fleet.html. Then there are other deployment models like using helm or ECK.

**Pull request merged**
