### PR TITLE
[Buildkite] Revamp buildkite scripts

### PR DESCRIPTION
**Pull request by mrodm**
Update buildkite scripts 

Tested:
- [x] PR pipeline
- [x] Pipeline test with integrations (https://buildkite.com/elastic/elastic-package-test-with-integrations) - [First test](https://buildkite.com/elastic/elastic-package-test-with-integrations/builds/82) - [Second test](https://buildkite.com/elastic/elastic-package-test-with-integrations/builds/84)

### CODE REVIEW

**Comment by mrodm** [comment]
test integrations

**Comment by mrodm** [comment]
test integrations

**Comment by mrodm** [comment]
test integrations

**Review by sharbuz — APPROVED** [review]
Looks good. Thank you @mrodm !
I only have one proposal: If we are going to use the common library of scripts I would start using universal (depending on the environment architecture) functions for installing some kind of tools where it's possible to avoid hardcoded "Linux", "x86_64" and so forth...

**Comment by mrodm** [comment]
> I only have one proposal: If we are going to use the common library of scripts I would start using universal (depending on the environment architecture) functions for installing some kind of tools where it's possible to avoid hardcoded "Linux", "x86_64" and so forth...

I'll create a follow PR for this @sharbuz ,thanks for the heads up!

**Pull request merged**
