### PR TITLE
Parallelize tests to shorten total time

### PR DESCRIPTION
**Pull request by mtojek**
This PR modifies the Jenkinsfile to parallelize test execution.

Please take a look at the pipeline graph.

### CODE REVIEW

**Comment by mtojek** [comment]
The total time decreased from 54 min to 31m. We can go lower if we remove few data streams from packages, as it was before. WDYT? @marc-gr

**Comment by marc-gr** [comment]
> The total time decreased from 54 min to 31m. We can go lower if we remove few data streams from packages, as it was before. WDYT? @marc-gr

Makes sense, I guess we just need to keep one for each of the packages?

**Comment by mtojek** [comment]
Yes, one representative data stream.

**Review by marc-gr — APPROVED** [review]

**Pull request merged**
