### PR TITLE
[Testing] Test if fleet-server policy by id is picked up

### PR DESCRIPTION
**Pull request by ruflin**

### CODE REVIEW

**Comment by mtojek** [comment]
@ruflin I think you need to add more context, what's going here :D

**Comment by ruflin** [comment]
I needed it to test https://github.com/elastic/beats/pull/25352 but pushed it as a PR to potentially discuss if this could be useful too.

**Comment by ruflin** [comment]
I'm going to close this as we don't need this exactly in this way for elastic-package.

@mtojek The part that is interesting about the change I have in this PR is that it is possible to preconfigure a base setup without having to do many API calls. This might simplify the elastic-package setup potentially.

**Comment by mtojek** [comment]
@ruflin 

When the [profiles](https://github.com/elastic/elastic-package/pull/301) feature lands in, user will be able to modify the stack setup and customize it based on needs (open ports, config options, etc.)

**Pull request closed without merging**
