### PR TITLE
Delete volumes when running docker compose down

### PR DESCRIPTION
**Pull request by jsoriano**
Remove volumes associated to scenarios when running docker-compose down.

### CODE REVIEW

**Review by mtojek — APPROVED** [review]
LGTM

Do you think we should mention this in the `--help` for the `down` command?

**Comment by jsoriano** [comment]
> LGTM
> 
> Do you think we should mention this in the `--help` for the `down` command?

Not sure, I would assume that no leftovers are left if the scenario is down.

**Comment by jsoriano** [comment]
I have found that the service have their own runner, added the flag there too. @mtojek could you take another look?

**Review by mtojek — APPROVED** [review]
WFG 

Please bump up the elastic-package dependency in elastic/integrations too.

**Comment by jsoriano** [comment]
Side note on this change, definitions like [this one](https://github.com/elastic/integrations/pull/1145/commits/a3be9183aee180fd1c924c482f2af723969ca5b6) may be needed for docker compose to be able to remove the volumes in some cases where the volume is defined in the dockerfile.

**Comment by mtojek** [comment]
Good catch. Maybe you should describe it also here: https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md

**Comment by mtojek** [comment]
I cleaned EC2 instances used by `elastic-packag test system`.

**Comment by jsoriano** [comment]
> Good catch. Maybe you should describe it also here: https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md

Docs added for this.

**Review by mtojek — APPROVED** [review]

**Pull request merged**
