### PR TITLE
Refactor  deprecated ioutil

### PR DESCRIPTION
**Pull request by mistikel**
With Go 1.16, the ioutil package is being deprecated: https://www.srcbeat.com/2021/01/golang-ioutil-deprecated/. We should start replacing its usage.

https://github.com/elastic/elastic-package/issues/231

### CODE REVIEW

**Comment by ycombinator** [comment]
Hi @mistikel, please break this PR up into two: one for addressing #231 and another for addressing #299. In general we prefer to keep PRs as tightly scoped as possible to make them easier to review, rollback changes if needed, etc. Also, in this case, one of the PR (the one for #231) depends on a version of Golang that we are not yet using in our build toolchain. Finally, please add some PR descriptions (what the PR is changing and why) along with links to related issues (which you did here). Thanks!

**Comment by ycombinator** [comment]
I also just noticed that you'll need to sign the [Elastic Contributor License Agreement (CLA)](https://www.elastic.co/contributor-agreement) before we can review and merge your PRs. Thanks again!

**Comment by mistikel** [comment]
@ycombinator I've updated it.

**Comment by mtojek** [comment]
Update to go1.16 already merged, closing this one.

**Pull request closed without merging**
