### PR TITLE
fix warn logger call

### PR DESCRIPTION
**Pull request by fearful-symmetry**
Fixes https://github.com/elastic/elastic-package/issues/370

This changes the warning function call, as it should be `warnf`.

### CODE REVIEW

**Review by ycombinator — APPROVED** [review]
LGTM.

**Comment by fearful-symmetry** [comment]
I think the CI errors are unrelated?

**Comment by ycombinator** [comment]
Yes, they are unrelated. I was able to reproduce the same error on `master`: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package/detail/master/115/tests.

**Comment by ycombinator** [comment]
Skipping the failing `apache.status` system test for now, while we investigate the failure, so as to unblock this and other PRs. See https://github.com/elastic/elastic-package/issues/374.

**Comment by ycombinator** [comment]
@fearful-symmetry Now that https://github.com/elastic/elastic-package/pull/375 has been merged, if you rebase this PR on `master`, CI should go green.

**Pull request merged**
