### PR TITLE
Neutral naming for elastic-package

### PR DESCRIPTION
**Pull request by v1v**
### What does this pull request do?

Neutral naming

### CODE REVIEW

**Comment by mtojek** [comment]
@v1v I see that this PR is broken (CI status). Is it ready for review or do you need an assistance here?

**Comment by v1v** [comment]
https://github.com/elastic/elastic-package/pull/652/commits/fca8a338d96cb05fe1ee49310ee3928c74716a4e should fix the linting issue now

**Review by mtojek — APPROVED** [review]
LGTM

**Comment by mtojek** [comment]
@v1v I see the red mark for `Configuration changed — The new Mergify configuration is valid`, but it's likely to expected?

**Comment by v1v** [comment]
> @v1v I see the red mark for Configuration changed — The new Mergify configuration is valid, but it's likely to be expected?

Unfortunately, we cannot verify functionally the mergify changes on a PR basis, only when it gets merged. 

It should not be an issue

**Pull request merged**
