### PR TITLE
Define minimal publishing pipeline

### PR DESCRIPTION
**Pull request by mtojek**
Related: https://github.com/elastic/elastic-package/pull/728

This PR adds a definition for a minimal publishing pipeline. I will implement the groovy files in follow-ups.

### CODE REVIEW

**Comment by jsoriano** [comment]
Is this pipeline going to be installed? I was thinking on a reference pipeline for documentation purpouses :slightly_smiling_face:

**Comment by mtojek** [comment]
Yeah, but this way it can be tested, so I thing it's still worth connecting it :)

**Comment by jsoriano** [comment]
> Yeah, but this way it can be tested, so I think it's still worth connecting it :)

Ok, but will this trigger the publication of any package? Or this job won't be ever triggered?

**Review by jsoriano — APPROVED** [review]

**Pull request merged**
