### PR TITLE
Try: use dummy service tokens

### PR DESCRIPTION
**Pull request by mtojek**
Related: https://github.com/elastic/kibana/issues/123113

### CODE REVIEW

**Comment by mtojek** [comment]
Currently struggling with:

```
[36mfleet-server_1               |[0m Kibana Fleet setup failed: http POST request to http://kibana:5601/api/fleet/setup fails: Access to Fleet API requires the superuser role and for stack security features to be enabled.: <nil>. Response: {"statusCode":403,"error":"Forbidden","message":"Access to Fleet API requires the superuser role and for stack security features to be enabled."}
```

**Comment by mtojek** [comment]
@nchaulet we're trying to enable service tokens. It worked for 8.0.0, but we're observing issues for 8.1.0-SNAPSHOT. Would you mind taking a look?

```
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","http.request.id":"01FSMA8YRG2G2DDJESQ6ZCVW42","mod":"enroll","fleet.enroll.apikey.id":"wm2kaH4BMg40PYJ8YCOR","error.message":"fail CreateAPIKey: [400 Bad Request] {\"error\":{\"root_cause\":[{\"type\":\"action_request_validation_exception\",\"reason\":\"Validation Failed: 1: An application name prefix must match the pattern ^[a-z][A-Za-z0-9]*$ (found '.fleet');\"}],\"type\":\"action_request_validation_exception\",\"reason\":\"Validation Failed: 1: An application name prefix must match the pattern ^[a-z][A-Za-z0-9]*$ (found '.fleet');\"},\"status\":400}","http.response.status_code":400,"event.duration":306104815,"@timestamp":"2022-01-17T15:25:17.251Z","message":"fail enroll"}
{"log.level":"error","ecs.version":"1.6.0","service.name":"fleet-server","http.request.id":"01FSMA8YRG2G2DDJESQ6ZCVW42","mod":"enroll","fleet.enroll.apikey.id":"wm2kaH4BMg40PYJ8YCOR","error.message":"fail CreateAPIKey: [400 Bad Request] {\"error\":{\"root_cause\":[{\"type\":\"action_request_validation_exception\",\"reason\":\"Validation Failed: 1: An application name prefix must match the pattern ^[a-z][A-Za-z0-9]*$ (found '.fleet');\"}],\"type\":\"action_request_validation_exception\",\"reason\":\"Validation Failed: 1: An application name prefix must match the pattern ^[a-z][A-Za-z0-9]*$ (found '.fleet');\"},\"status\":400}","@timestamp":"2022-01-17T15:25:17.251Z","message":"perform rollback on enrollment failure"}
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","http.request.id":"01FSMA8YRG2G2DDJESQ6ZCVW42","url.full":"/api/fleet/agents/enroll","http.version":"1.1","http.request.method":"POST","fleet.apikey.id":"wm2kaH4BMg40PYJ8YCOR","client.address":"127.0.0.1:45034","tls.established":false,"http.request.body.bytes":625,"http.response.body.bytes":39,"http.response.status_code":400,"event.duration":306219702,"@timestamp":"2022-01-17T15:25:17.251Z","message":"HTTP done"}
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","status":"STOPPING","@timestamp":"2022-01-17T15:25:17.252Z","message":"Stopping"}
```

**Comment by mtojek** [comment]
The error above is unrelated and should be fixed with https://github.com/elastic/fleet-server/pull/1091.

**Review by jsoriano — APPROVED** [review]

**Pull request merged**
