### PR TITLE
Switch to PAT generated GH token

### PR DESCRIPTION
**Pull request by ev1yehor**
Switch to PAT generated GH token

Linked issue:
- https://github.com/elastic/ingest-dev/issues/3495

### CODE REVIEW

**Comment by ev1yehor** [comment]
test integrations

**Comment by ev1yehor** [comment]
test integrations

**Comment by ev1yehor** [comment]
Tested in pipeline https://buildkite.com/elastic/elastic-package-test-with-integrations/builds/175#0190e4cc-f78a-47a4-9ef6-db79d96fca0f

**Review by jsoriano — APPROVED** [review]
Thanks!

**Pull request merged**
