### PR TITLE
Add retries to kibana client

### PR DESCRIPTION
**Pull request by jsoriano**
Adding it by now only to kibana client because for elasticsearch client we rely on the Go SDK, that has its own retry mechanisms.

As it is implemented, we can later consider using it in more places where an http client is used now.

### CODE REVIEW

**Review by mrodm — APPROVED** [review]
Nice!
Did you test these changes creating a serverless project?

**Comment by jsoriano** [comment]
> Nice! Did you test these changes creating a serverless project?

No... let me try...

**Comment by jsoriano** [comment]
> Did you test these changes creating a serverless project?

Tested to start and stop serverless four times, and all of them were successful, except one where elastic-agent failed to start due to some authentication error, that seemed unrelated to this change. Running up again in this case started the agent.

I saw some retries querying status endpoints, and the debug logging was different. I have configured it to use the default `slog` logger that fulfils the requirements for `retryablehttp` and uses `log` under the hood as we do everywhere else.

**Review by mrodm — APPROVED** [review]
:rocket: 

> Tested to start and stop serverless four times, and all of them were successful, except one where elastic-agent failed to start due to some authentication error, that seemed unrelated to this change. Running up again in this case started the agent.

Thanks for checking this out ! 

> I saw some retries querying status endpoints, and the debug logging was different. I have configured it to use the default slog logger that fulfils the requirements for retryablehttp and uses log under the hood as we do everywhere else.

First usage of `slog` :muscle: At some point I would like to start using more that package

**Pull request merged**
