### PR TITLE
Use staticcheck instead of golint

### PR DESCRIPTION
**Pull request by jsoriano**
Golint is discontinued, migrate to [staticcheck](https://staticcheck.io). (see https://github.com/golang/go/issues/44354#issuecomment-835504889).

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]

**Comment by mdelapenya** [comment]
As a follow-up improvement, have you thought about integrating pre-commit? https://pre-commit.com/hooks.html It does support `staticcheck`

**Comment by jsoriano** [comment]
Failing test is failing in other branches too.

**Comment by jsoriano** [comment]
> Failing test is failing in other branches too.

PR open to skip the failing test https://github.com/elastic/elastic-package/pull/504

**Review by mdelapenya — APPROVED** [review]

**Pull request merged**
