### PR TITLE
[Kubernetes] Add support for 1.26 K8s version and update kind version

### PR DESCRIPTION
**Pull request by constanca-m**
## What does this PR do?
Adds support for Kubernetes 1.26.x version and update kind version to 0.17.0

## Related issues

- Relates to https://github.com/elastic/observability-dev/issues/2345

### CODE REVIEW

**Review by jsoriano — APPROVED** [review]

**Comment by constanca-m** [comment]
\test

**Comment by tetianakravchenko** [comment]
@Mergifyio rebase

**Pull request merged**
